apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-deployment
  labels:
    app: world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world
  template:
    metadata:
      labels:
        app: world
    spec:
      containers:
      - name: world
        image: art/world-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: world-service
spec:
  type: NodePort
  selector:
    app: world
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

